version: '3'
services:
        db:
                image: mysql
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - db_data:/var/lib/mysql
                        - ./mysql_custom:/docker-entrypoint-initdb.d
                restart: always
                ports:
                         - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: toor
                        MYSQL_DATABASE: gstore
                        MYSQL_USER: gaetan
                        MYSQL_PASSWORD: password

        gamestore:
                depends_on:
                        - db
                build: .
                restart: always
                links:
                        - db
                ports:
                        - "80:80"
volumes:
        db_data: {}
